version: '3'

services:
  neo4j:
    image: neo4j:5.17.0-community-bullseye
    container_name: my_neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
  python:
    build: ./python_docker
    container_name: my_python3
    tty: true
    volumes:
      -  ./src:/home/src